
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.text.DateFormatter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author dumza
 */
public class DV_GUI extends javax.swing.JFrame {

    /**
     * Creates new form DV_GUI
     */
    public DV_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblShadow1 = new javax.swing.JLabel();
        txfName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        radFillings = new javax.swing.JRadioButton();
        radBraces = new javax.swing.JRadioButton();
        radCheckUp = new javax.swing.JRadioButton();
        radIssue = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jarDatePicker = new com.toedter.calendar.JDateChooser();
        btnBook = new javax.swing.JButton();
        cbxAge = new javax.swing.JComboBox<>();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 51));
        setForeground(new java.awt.Color(204, 51, 0));
        setMaximumSize(new java.awt.Dimension(640, 360));
        setMinimumSize(new java.awt.Dimension(640, 360));
        setResizable(false);
        getContentPane().setLayout(null);

        lblTitle.setFont(new java.awt.Font("Bebas Kai", 0, 48)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 153, 255));
        lblTitle.setText("SAKURA DENTAL CLINIC");
        getContentPane().add(lblTitle);
        lblTitle.setBounds(150, 34, 351, 58);

        lblShadow1.setFont(new java.awt.Font("Bebas Kai", 0, 48)); // NOI18N
        lblShadow1.setForeground(new java.awt.Color(102, 102, 102));
        lblShadow1.setText("SAKURA DENTAL CLINIC");
        getContentPane().add(lblShadow1);
        lblShadow1.setBounds(150, 40, 355, 50);

        txfName.setFont(new java.awt.Font("Pokemon GB", 0, 8)); // NOI18N
        txfName.setForeground(new java.awt.Color(153, 0, 153));
        txfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfNameActionPerformed(evt);
            }
        });
        getContentPane().add(txfName);
        txfName.setBounds(237, 110, 122, 30);

        lblName.setFont(new java.awt.Font("Bebas Kai", 0, 12)); // NOI18N
        lblName.setText("Name");
        getContentPane().add(lblName);
        lblName.setBounds(150, 114, 41, 15);

        radFillings.setFont(new java.awt.Font("Bebas Kai", 0, 12)); // NOI18N
        radFillings.setForeground(new java.awt.Color(51, 255, 255));
        radFillings.setText("Fillings");
        radFillings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radFillingsActionPerformed(evt);
            }
        });
        getContentPane().add(radFillings);
        radFillings.setBounds(237, 200, 70, 18);

        radBraces.setFont(new java.awt.Font("Bebas Kai", 0, 12)); // NOI18N
        radBraces.setForeground(new java.awt.Color(51, 255, 255));
        radBraces.setText("Braces");
        radBraces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBracesActionPerformed(evt);
            }
        });
        getContentPane().add(radBraces);
        radBraces.setBounds(313, 200, 65, 18);

        radCheckUp.setFont(new java.awt.Font("Bebas Kai", 0, 12)); // NOI18N
        radCheckUp.setForeground(new java.awt.Color(51, 255, 255));
        radCheckUp.setText("Check up");
        radCheckUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radCheckUpActionPerformed(evt);
            }
        });
        getContentPane().add(radCheckUp);
        radCheckUp.setBounds(384, 200, 78, 18);

        radIssue.setFont(new java.awt.Font("Bebas Kai", 0, 12)); // NOI18N
        radIssue.setText("Issue");
        getContentPane().add(radIssue);
        radIssue.setBounds(150, 200, 41, 15);

        lblAge.setFont(new java.awt.Font("Bebas Kai", 0, 12)); // NOI18N
        lblAge.setText("Age Group");
        getContentPane().add(lblAge);
        lblAge.setBounds(150, 161, 60, 15);

        lblDate.setFont(new java.awt.Font("Bebas Kai", 0, 12)); // NOI18N
        lblDate.setText("Booking Date");
        getContentPane().add(lblDate);
        lblDate.setBounds(150, 245, 60, 15);

        jarDatePicker.setForeground(new java.awt.Color(255, 204, 255));
        jarDatePicker.setDateFormatString("yyyy-LL-dd");
        getContentPane().add(jarDatePicker);
        jarDatePicker.setBounds(237, 239, 145, 29);

        btnBook.setFont(new java.awt.Font("Bebas Kai", 0, 12)); // NOI18N
        btnBook.setForeground(new java.awt.Color(51, 0, 51));
        btnBook.setText("Book Appointment");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });
        getContentPane().add(btnBook);
        btnBook.setBounds(144, 279, 150, 35);

        cbxAge.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100", " " }));
        cbxAge.setToolTipText("Eg. 0 means 0-9yrs and 70 means 70-79");
        cbxAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAgeActionPerformed(evt);
            }
        });
        getContentPane().add(cbxAge);
        cbxAge.setBounds(237, 158, 122, 22);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Erzawallpaper.png"))); // NOI18N
        getContentPane().add(lblBackground);
        lblBackground.setBounds(-890, -580, 1540, 950);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfNameActionPerformed

    private void radFillingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radFillingsActionPerformed
        radBraces.setSelected(false);
        radCheckUp.setSelected(false);
    }//GEN-LAST:event_radFillingsActionPerformed

    private void radBracesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBracesActionPerformed
        radFillings.setSelected(false);
        radCheckUp.setSelected(false);
    }//GEN-LAST:event_radBracesActionPerformed

    private void radCheckUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radCheckUpActionPerformed
        radBraces.setSelected(false);
        radFillings.setSelected(false);
    }//GEN-LAST:event_radCheckUpActionPerformed


    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        if (txfName.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "PLEASE ENTER A NAME?");
        } else {
            if (!radFillings.isSelected() && !radBraces.isSelected()
                    && !radCheckUp.isSelected()) {
               JOptionPane.showMessageDialog(null, "PLEASE SELECT YOUR ISSUE?");
            } else {
                if (radFillings.isSelected()
                        && Integer.parseInt(cbxAge.getSelectedItem().toString())
                        == 0) {
                    JOptionPane.showMessageDialog(null,
                            "AGE GROUP 0 IS NOT ELIGIBLE FOR FILLINGS");
                } else {
                    if (radBraces.isSelected()
                            && Integer.parseInt
                        (cbxAge.getSelectedItem().toString()) == 0) {
                        JOptionPane.showMessageDialog(null,
                                "AGE GROUP 0 IS NOT ELIGIBLE FOR BRACES");
                    }
                    else
                    {
                        if(jarDatePicker.getDate() == null)
                        {
                            JOptionPane.showMessageDialog(null, 
                                    "PLEASE ENTER A DATE?");
                        }
                        else
                        {
                            
                                        
                            LocalDate today = LocalDate.now();
                            Date sDate = jarDatePicker.getDate();
                            SimpleDateFormat formatter = new 
                            SimpleDateFormat("yyyy-LL-dd");
                            String dateString = formatter.format(sDate);
                            LocalDate aDate = LocalDate.parse(dateString,
                                    DateTimeFormatter.ofPattern("yyyy-LL-dd"));
                            if (aDate.isBefore(today))
                            {
                                JOptionPane.showMessageDialog(null, "PLEASE"
                                        + " ENTER A VALID DATE?"
                                        + "\n- You have booked for a date"
                                        + " that has already passed.");
                            }
                            else
                            {
                                if(Integer.parseInt(cbxAge.getSelectedItem()
                                  .toString()) >= 40 && radCheckUp.isSelected())
                                {
                                    JOptionPane.showMessageDialog(null,
                                      "APPOINTMENT BOOKED"
                                              + "\n- You also qualify"
                                              + " to recieve dentures.");
                                this.setVisible(false);
                                this.dispose();
                                }
                                else
                                {
                                    JOptionPane.showMessageDialog(null,
                                            "APPOINTMENT BOOKED");
                                    this.setVisible(false);
                                    this.dispose();
                                }
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_btnBookActionPerformed

    private void cbxAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxAgeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DV_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DV_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DV_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DV_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DV_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook;
    private javax.swing.JComboBox<String> cbxAge;
    private com.toedter.calendar.JDateChooser jarDatePicker;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblShadow1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton radBraces;
    private javax.swing.JRadioButton radCheckUp;
    private javax.swing.JRadioButton radFillings;
    private javax.swing.JLabel radIssue;
    private javax.swing.JTextField txfName;
    // End of variables declaration//GEN-END:variables
}
